---
# Playbook to Create GKE Cluster

- name: Create a GKE Cluster
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"

  roles:
    - network_create
    - gke_cluster_create