---
# Playbook to undeploy Ghost and its component

- name: Undeploy Ghost App
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"

  roles:
    - {role: gke_app_destroy, tags: 'gke_app_destroy'}
  tags:
    - destroy_deployment
