---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:latest
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "http://my-ghost-blog.com/"