---

- name: Install Kubernetes package
  package:
    name: kubelet
    state: present

- name: Start and enable the Kubernetes service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Create a deployment for Ghost
  host: localhost
  template:
    src: ghost-deployment.yaml
    dest: /etc/kubernetes/manifests/ghost-deployment.yaml
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Create a service for Ghost
  template:
    src: ghost-service.yaml
    dest: /etc/kubernetes/manifests/ghost-service.yaml
    owner: root
    group: root
    mode: 0644
    force: yes